### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by dinotheextinct** [Bismuth-Forge/bismuth#424] opened 2022-09-08 07:26 UTC
### Summary

Wrong tiling for KDE/System windows on wayland.

### Steps to Reproduce

Open any kind of KDE System settings window and recognize wrong tiling.

### Expected behavior

Normal tiling for all windows.

### Screenshots

![tiling_prob](https://user-images.githubusercontent.com/32158581/189060703-6557ce3c-4e34-48e8-9e16-df78418afc5e.png)

### Bismuth version

3.1.3-13.1

### KDE Plasma version

5.25.4

### The platform KWin is running on

Wayland

**Comment by verahawk** [comment] 2022-09-11 09:50
Have you tried setting the minimum size of the KDE settings window to some small value?
https://github.com/Bismuth-Forge/bismuth/blob/master/docs/TWEAKS.md#setting-minimum-geometry-size

**Comment by dinotheextinct** [comment] 2022-09-12 15:18
Sadly it doesnt fix the issue.

**Comment by gikari** [comment] 2022-09-13 11:51
Duplicate of #102

**Closed by gikari** 2022-09-13 11:51 UTC
Labels: bug
