### ISSUE TITLE
[Bug]: Upon upgrade from 2.3.0, keyboard shortcuts stop working

### ISSUE THREAD

**Issue by DIzFer** [Bismuth-Forge/bismuth#306] opened 2022-02-21 10:59 UTC
I ended up with the same binding assigned under both the new bismuth category and the legacy kwin one. This resulted in bismuth shortcuts not working at all, simply passing through to the active window.

The only way I managed to reproduce the problem by manually editing `kglobalshortcutsrc` to assign the same keybind to two shortcuts.

Unless I'm missing something in [here](https://techbase.kde.org/Development/Tools/Using_kconf_update), the old group should not have remained in any way or form.

I cannot be 100% sure, but, the most likely cause for this to happen on its own might have been running bismuth versions from before  f7300cd5f8281742e25461520522e886d19fe35d _after the kconf update has happened_.

In my case, the relevant borked file was in `~/.config/kglobalshortcutsrc`, and had this content (among ~400 lines):

```dosini
[bismuth]
_k_friendly_name=Window Tiling
decrease_master_size=Meta+Ctrl+J,none,Decrease Master Area Size
decrease_master_win_count=none,Meta+[,Decrease Master Area Window Count
decrease_window_height=none,Meta+Ctrl+K,Decrease Window Height
decrease_window_width=none,Meta+Ctrl+H,Decrease Window Width
focus_bottom_window=Meta+J,Meta+J,Focus Bottom Window
focus_left_window=Meta+H,Meta+H,Focus Left Window
focus_next_window=none,none,Focus Next Window
focus_prev_window=none,none,Focus Previous Window
focus_right_window=Meta+L,Meta+L,Focus Right Window
focus_upper_window=Meta+K,Meta+K,Focus Upper Window
increase_master_size=Meta+Ctrl+K,none,Increase Master Area Size
increase_master_win_count=none,Meta+],Increase Master Area Window Count
increase_window_height=none,Meta+Ctrl+J,Increase Window Height
increase_window_width=none,Meta+Ctrl+L,Increase Window Width
move_window_to_bottom_pos=Meta+Shift+J,Meta+Shift+J,Move Window Down
move_window_to_left_pos=Meta+Shift+H,Meta+Shift+H,Move Window Left
move_window_to_next_pos=none,none,Move Window to the Next Position
move_window_to_prev_pos=none,none,Move Window to the Previous Position
move_window_to_right_pos=Meta+Shift+L,Meta+Shift+L,Move Window Right
move_window_to_upper_pos=Meta+Shift+K,Meta+Shift+K,Move Window Up
next_layout=Meta+Return,Meta+\\\\,Switch to the Next Layout
prev_layout=none,Meta+|,Switch to the Previous Layout
push_window_to_master=Meta+PgUp,Meta+Return,Push Active Window to Master Area
rotate=Meta+R,Meta+R,Rotate
rotate_part=Meta+Shift+R,Meta+Shift+R,Rotate Part
rotate_reverse=none,none,Rotate (Reverse)
toggle_float_layout=none,Meta+Shift+F,Toggle Floating Layout
toggle_monocle_layout=none,Meta+M,Toggle Monocle Layout
toggle_quarter_layout=none,none,Toggle Quarter Layout
toggle_spiral_layout=none,none,Toggle Spiral Layout
toggle_spread_layout=none,none,Toggle Spread Layout
toggle_stair_layout=none,none,Toggle Stair Layout
toggle_three_column_layout=none,none,Toggle Three Column Layout
toggle_tile_layout=none,Meta+T,Toggle Tile Layout
toggle_window_floating=Meta+Esc,Meta+F,Toggle Active Window Floating

# other stuff

[kwin]
# more stuff
bismuth_decrease_master_size=none,none,Bismuth: Decrease Master Area Size
bismuth_decrease_master_win_count=Meta+[,none,Bismuth: Decrease Master Area Window Count
bismuth_decrease_window_height=none,none,Bismuth: Decrease Window Height
bismuth_decrease_window_width=Meta+Ctrl+H,none,Bismuth: Decrease Window Width
bismuth_focus_bottom_window=none,none,Bismuth: Focus Bottom Window
bismuth_focus_left_window=none,none,Bismuth: Focus Left Window
bismuth_focus_next_window=none,none,Bismuth: Focus Next Window
bismuth_focus_prev_window=none,none,Bismuth: Focus Previous Window
bismuth_focus_right_window=none,none,Bismuth: Focus Right Window
bismuth_focus_upper_window=none,none,Bismuth: Focus Upper Window
bismuth_increase_master_size=none,none,Bismuth: Increase Master Area Size
bismuth_increase_master_win_count=Meta+],none,Bismuth: Increase Master Area Window Count
bismuth_increase_window_height=none,none,Bismuth: Increase Window Height
bismuth_increase_window_width=Meta+Ctrl+L,none,Bismuth: Increase Window Width
bismuth_move_window_to_bottom_pos=none,none,Bismuth: Move Window Down
bismuth_move_window_to_left_pos=none,none,Bismuth: Move Window Left
bismuth_move_window_to_next_pos=none,none,Bismuth: Move Window to the Next Position
bismuth_move_window_to_prev_pos=none,none,Bismuth: Move Window to the Previous Position
bismuth_move_window_to_right_pos=none,none,Bismuth: Move Window Right
bismuth_move_window_to_upper_pos=none,none,Bismuth: Move Window Up
bismuth_next_layout=Meta+\\\\,none,Bismuth: Switch to the Next Layout
bismuth_prev_layout=Meta+|,none,Bismuth: Switch to the Previous Layout
bismuth_push_window_to_master=none,none,Bismuth: Push Active Window to Master Area
bismuth_rotate=none,none,Bismuth: Rotate
bismuth_rotate_part=none,none,Bismuth: Rotate Part
bismuth_rotate_reverse=none,none,Bismuth: Rotate (Reverse)
bismuth_toggle_float_layout=none,none,Bismuth: Toggle Floating Layout
bismuth_toggle_monocle_layout=Meta+M,none,Bismuth: Toggle Monocle Layout
bismuth_toggle_quarter_layout=none,none,Bismuth: Toggle Quarter Layout
bismuth_toggle_spiral_layout=none,none,Bismuth: Toggle Spiral Layout
bismuth_toggle_spread_layout=none,none,Bismuth: Toggle Spread Layout
bismuth_toggle_stair_layout=none,none,Bismuth: Toggle Stair Layout
bismuth_toggle_three_column_layout=none,none,Bismuth: Toggle Three Column Layout
bismuth_toggle_tile_layout=none,none,Bismuth: Toggle Tile Layout
bismuth_toggle_window_floating=Meta+Esc,none,Bismuth: Toggle Active Window Floating
```

For example,  Meta+Esc is assigned twice, and therefore doesn't work.

The keys under the [bismuth] group are the correct ones for anything post-2.3.0. Removing the unused keys let my shortcuts work again.

**Comment by gikari** [comment] 2022-03-20 08:06
Could you reproduce this with a new release?

**Comment by HanabishiRecca** [comment] 2022-03-20 10:55
Keybinding seems to be bugged a bit. But it's more like KDE is confused, not the Bismuth bug.
I found a way to fix it. Just reassign not working hotkey to something else, apply changes, then reassign back. It will start to work again.

**Comment by gikari** [comment] 2022-03-20 11:01
Ok, then I will close this.

**Closed by gikari** 2022-03-20 11:01 UTC
Labels: bug, needs more info

**Comment by 5310** [comment] 2022-03-21 09:17
@HanabishiRecca This fixed my monocle toggle shortcut, thanks! But I can't figure out to invoke that shortcut from the command line anymore, can you please help a bit?

I use a button on my panel to toggle monocle on and off. So far I've been using the following command to invoke that same shortcut so far. But now that doesn't work:
```qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut bismuth_toggle_monocle_layout"```

**Comment by HanabishiRecca** [comment] 2022-03-21 09:31
I suppose that the problem is `bismuth_toggle_monocle_layout`. Old shortcuts under `[kwin]` no longer used. You need to look for shortcuts under `[bismuth]` category.

**Comment by 5310** [comment] 2022-03-21 09:36
Thank you again! That worked! I am now using:
```
qdbus org.kde.kglobalaccel /component/bismuth org.kde.kglobalaccel.Component.invokeShortcut "toggle_monocle_layout"
```

Is this introduciton of categories explained somewhere that I can read up about?

**Comment by HanabishiRecca** [comment] 2022-03-21 10:06
> Is this introduciton of categories explained somewhere that I can read up about?

Read [v3.0.0 changelog](https://github.com/Bismuth-Forge/bismuth/releases/tag/v3.0.0)
