### ISSUE TITLE
[Bug]: Kwins Move to Next Screen is broken on 5.25 (Wayland) with bismuth

### ISSUE THREAD

**Issue by DashieTM** [Bismuth-Forge/bismuth#374] opened 2022-06-16 21:29 UTC
### Summary

The move to next screen command doesn't work when used on tiled electron apps such as spotify, element, etc.
For other apps the leftmost screen seems to not work in 1 direction.
Aka I can move to the next screen from right all the way to the left, but can't go back right from that screen. I have to continue going left for some reason.

Please check the video for an easier comprehension.

Note, the command works 100% fine on UNTILED windows.

I have also tried fixing it with various window rules, but have not found any success in that as I had before the 5.25 update.

Sidenote, it also seems to have gotten some performance issues on my system, but it is hard to determine what the problem is exactly.

### Steps to Reproduce

The electron Problem:
1. Start a wayland session.
2. Open an electron app.
3. try to move the app with the move to next screen command
4. If it works once, try again until it breaks.

The other apps:
1. Start a wayland session.
5. Open any app.
6. try to use the move to the next screen shortcut from kwin from the rightmost screen.
7. continue until you arrive at leftmost screen
8. try to move back to the right.

### Expected behavior

electron apps:
window moves according to command
However it does a few times and for me only to the left, any command to the right doesn't work at all.

other apps:
window moves back to the right 

### Screenshots

https://user-images.githubusercontent.com/72016555/174169130-1a0a7af6-2557-4ea7-b5af-cb735d06862b.mp4

While nothing happens, or some applications are flickering, I am wildly spamming the move window to x screen buttons.

### Bismuth version

3.1.1 (direct pull from master!)

### KDE Plasma version

5.25

### The platform KWin is running on

Wayland

**Comment by HelmicNewciv** [comment] 2022-06-18 06:59
Having a similar problem on X11.  Still trying to pin down the exact behavior, but it's got a similar flickering thing going on.

**Comment by Mewsen** [comment] 2022-06-18 12:54
I have the same issue, also on wayland !

**Comment by benemorius** [comment] 2022-06-18 18:54
This seems a likely duplicate of #370 although wayland might need different treatment. There's a fix in that thread but I haven't tested on wayland.

**Comment by DashieTM** [comment] 2022-06-18 19:01
> This seems a likely duplicate of #370 although wayland might need different treatment. There's a fix in that thread but I haven't tested on wayland.

It is not a real duplicate as this issue was fixable via kwin rules on 5.24. Sadly this is no longer the case.
However the cause for the bug is likely the same.
aka a previous workaround now no longer works, which is why I opened this bug report.

I can ofc not say what the issue is since I am not a KDE developer, but something they did broke bismuth on 5.25.

**Comment by benemorius** [comment] 2022-06-18 19:11
@DashieTM can you confirm that the fix in #370 doesn't work on wayland?

**Comment by DashieTM** [comment] 2022-06-18 19:19
> @DashieTM can you confirm that the fix in #370 doesn't work on wayland?

I first thought the No Border was the fix, then I saw the link to your fork, i changed that line as well. 
Seems like this did fix the move to x screen command.
Spotify is bugged now in terms of moving around generally, and the animations are a bit off compared to 5.24.
Perhaps that's the cost of the arrange command? 

Either way create a PR, this has been a major problem for quite a while, nice work!

**Comment by benemorius** [comment] 2022-06-18 19:23
I'm not sure it's the right way to fix it but I'm looking in to it. Somehow I only discovered Bismuth this morning so I'm still catching up.

**Comment by ZackGlenn** [comment] 2022-07-03 17:54
This PR fixes the problem for me. Without it, the I only way I can move windows between monitors is to float -> move -> unfloat.

**Closed** 2022-09-02 11:30 UTC
Labels: bug
