### ISSUE TITLE
[FEATURE]: New layout

### ISSUE THREAD

**Issue by ForteDexe** [Bismuth-Forge/bismuth#304] opened 2022-02-19 21:11 UTC
### A clear and concise description of what you want to happen

The new window will split the old window (or the window under the mouse cursor) in half.
```
If old_window_w < old_window_h:
   split horizontal
else:
   split vertical

If hold a short while draging a window to another window will split it too.
```

By this way, it is freer to organize the window layout.

**Comment by gikari** [comment] 2022-02-21 12:11
This is a duplicate of #182

**Closed by gikari** 2022-02-21 12:11 UTC
Labels: enhancement
