### ISSUE TITLE
Bismuth shortcuts not working

### ISSUE THREAD

**Issue by YassinRian** [Bismuth-Forge/bismuth#339] opened 2022-04-07 10:58 UTC
Hi, 
I have recently installed Bismuth for KDE plasma. Everything seemed to work fine, but after a couple of days the Bismuth shortcuts (under kwin shortcuts) are not working anymore. Someone else experiencing the same or any adivice ?

**Comment by gikari** [comment] 2022-04-07 11:06
Duplicate of #336

**Closed by gikari** 2022-04-07 11:06 UTC
